### ISSUE TITLE
hidden comments

### ISSUE THREAD

**Issue by iacoco** [medialab-prado/consul#120]
Example and proposal:

Set A : "transparencia pública" => comment (central) 
Set B : "necesidad de una mayor transparencia pública" => comment (izquierda) 
Subset ob B not intersected with A: "necesidad de una mayor"

A is included into B.  A is hidden. We can not access to A.

In general always a comment is included in a bigger comment remains hidden.

The proposal to solve this issue is the same applied here "https://decide.madrid.es/proceso/alianza-gobierno-abierto-borrador"

When you click over a point you will see the "box&debate" with all comments of sets which include that point.

In the example:
If you click over A you´ll see comments of A and B.
If you click over the subset of B not intersected with A you´ll see just the comments of B.

**Comment by amaia** [comment]
hey @iacoco, we've improved the way hightlighting works and now the comments for set A are not hidden by comments of set B, you can click on set A and get the highlight and comments just for that part

**Comment by iacoco** [comment]
the problem remains.
set A + set B = Set C
Comments for C are hidden. Try that.

I think is better our proposal. This way also comments are not scattered and there is a simple way to group them.

**Comment by furilo** [comment]
@iacoco if we do as you say, we would have to generate various complete boxes, one for each set. As in:

![screen shot 2017-02-23 at 17 27 28](https://cloud.githubusercontent.com/assets/24740/23268502/4138595c-f9ee-11e6-8340-7eac22ec1449.png)

If you want, we can go with this option, although in the future it would be good to devote some time to improve the design (doing it now is not really an option for us as we are way over the contracted hours ;)

So please confirm which way you want it: current, or as in the screenshot.

**Comment by iacoco** [comment]
It´s not possible to regroup comments in one box ?  I think is not acceptable to hide comments, I think this was clearly defined in the session we had some weeks ago. I f you want we can talk tomorrow.

**Comment by ferblape** [comment]
@iacoco it is possible to regroup them, but they do belong to different text selections:

- the first 3 comments belong to the long paragraph "Este reto, que constituye al mismo tiempo..."
- the second comment belongs to the text selection "Siglo XXI"

These are our concerns:

- What if I want to highlight just "Siglo XXI" and comment just about that?  Why should I see the rest of the comments of a text I haven't selected?
- Why if I have selected a long paragraph because I want to comment all of it, I also see the comments of the small annotations contained on it?
- **each annotation thread has a permalink**, what if I'm seeing the permalink of the long paragraph and I see comments of other annotations? Really confusing too.

From the point of view of the user it's not clear at all and that's why we are allowing  the annotations and the comments of each annotation to live separately. 

And we don't think comments are hidden, they are highlighted in different levels of yellow, so it's easy to detect where are different comments overlapped.

**Comment by amaia** [comment]
@iacoco @furilo @ferblape I've deployed the change to show several comments boxes to staging, please check it out and let's see if that solves the problem of hidden comments

**Comment by furilo** [comment]
@iacoco @rxnetwalker please take a look: https://consul.gobify.net/legislation/processes/3/draft_versions/4

**Comment by iacoco** [comment]
Hola

Entendí que esto de crear varias cajas era sólo para la situación en la que
quedaba oculto un comentario. Ahora se crean cajas diferentes siempre que
pulsas en un punto en el que hay varios subrayados. Esto implica que
prácticamente en muchos casos van a aparecer dos cajas. Lo que creo que
crea confusión. De la otra forma sólo en ocasiones muy concretas
aparecerían dos cajas.
¿No se puede dejar sólo varias cajas cuando queda oculto uno comentario ?

2017-02-27 11:44 GMT+01:00 Álvaro Ortiz <notifications@github.com>:
